# Generated by Django 6.0.4 on 2026-05-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
