from django.urls import path
from .views import (
    MyProfileView, 
    ProfileSubmitView,
    MyScoresView,
    DocumentListUploadView, 
    DocumentDeleteView,
    CatalogListView,
    ApplicationListView,
    ApplicationDetailView,
    MajorStatsView,
    PaymentStatusView,
    PaymentInitView,
    PaymentCallbackView,
    AdminProfileListView,
    AdminProfileDetailView,
    AdminVerifyProfileView,
    AdminVerifyDocumentView,
    AdminConfirmPaymentView,
    AdminDashboardStatsView,
    AdminMajorCRUDView,
    AdminCombinationCRUDView,
    AdminFormulaCRUDView,
    AdminRankingView,
    AdminPublishResultView,
    AdminMajorBenchmarkCRUDView,
    AdminPublishBenchmarkView,
    AdminExportResultCSVView,
    AdminSendAdmissionEmailsView,
    AdminMajorWorkflowStatusView,
    CandidateAdmissionLetterDataView,
    AdminSeasonCRUDView,
)

urlpatterns = [
    # Candidate routes
    path('profile/me/', MyProfileView.as_view(), name='my-profile'),
    path('profile/submit/', ProfileSubmitView.as_view(), name='profile-submit'),
    path('profile/scores/', MyScoresView.as_view(), name='my-scores'),
    path('documents/', DocumentListUploadView.as_view(), name='documents-list-upload'),
    path('documents/<uuid:doc_id>/', DocumentDeleteView.as_view(), name='document-delete'),
    path('catalogs/', CatalogListView.as_view(), name='catalogs-list'),
    path('applications/', ApplicationListView.as_view(), name='applications-list'),
    path('applications/<uuid:app_id>/', ApplicationDetailView.as_view(), name='application-detail'),
    path('stats/majors/', MajorStatsView.as_view(), name='major-stats'),
    path('payments/status/', PaymentStatusView.as_view(), name='payment-status'),
    path('payments/init/', PaymentInitView.as_view(), name='payment-init'),
    path('payments/callback/', PaymentCallbackView.as_view(), name='payment-callback'),
    path('admission-letter/', CandidateAdmissionLetterDataView.as_view(), name='candidate-admission-letter'),
    
    # Admin routes
    path('admin/profiles/', AdminProfileListView.as_view(), name='admin-profiles-list'),
    path('admin/profiles/<uuid:profile_id>/', AdminProfileDetailView.as_view(), name='admin-profile-detail'),
    path('admin/profiles/<uuid:profile_id>/verify/', AdminVerifyProfileView.as_view(), name='admin-profile-verify'),
    path('admin/documents/<uuid:doc_id>/verify/', AdminVerifyDocumentView.as_view(), name='admin-document-verify'),
    path('admin/profiles/<uuid:profile_id>/confirm-payment/', AdminConfirmPaymentView.as_view(), name='admin-confirm-payment'),
    path('admin/dashboard-stats/', AdminDashboardStatsView.as_view(), name='admin-dashboard-stats'),
    path('admin/majors/', AdminMajorCRUDView.as_view(), name='admin-majors-list'),
    path('admin/majors/<uuid:pk>/', AdminMajorCRUDView.as_view(), name='admin-majors-detail'),
    path('admin/combinations/', AdminCombinationCRUDView.as_view(), name='admin-combinations-list'),
    path('admin/combinations/<uuid:pk>/', AdminCombinationCRUDView.as_view(), name='admin-combinations-detail'),
    path('admin/formulas/', AdminFormulaCRUDView.as_view(), name='admin-formulas-list'),
    path('admin/formulas/<uuid:pk>/', AdminFormulaCRUDView.as_view(), name='admin-formulas-detail'),
    path('admin/ranking/<uuid:major_id>/', AdminRankingView.as_view(), name='admin-ranking'),
    path('admin/ranking/<uuid:major_id>/publish/', AdminPublishResultView.as_view(), name='admin-publish-result'),
    path('admin/ranking/<uuid:major_id>/publish-benchmark/', AdminPublishBenchmarkView.as_view(), name='admin-publish-benchmark'),
    path('admin/ranking/<uuid:major_id>/export-csv/', AdminExportResultCSVView.as_view(), name='admin-export-csv'),
    path('admin/ranking/<uuid:major_id>/send-emails/', AdminSendAdmissionEmailsView.as_view(), name='admin-send-emails'),
    path('admin/ranking/<uuid:major_id>/workflow-status/', AdminMajorWorkflowStatusView.as_view(), name='admin-workflow-status'),
    path('admin/benchmarks/', AdminMajorBenchmarkCRUDView.as_view(), name='admin-benchmarks-list'),
    path('admin/benchmarks/<uuid:pk>/', AdminMajorBenchmarkCRUDView.as_view(), name='admin-benchmarks-detail'),
    path('admin/seasons/', AdminSeasonCRUDView.as_view(), name='admin-seasons-list'),
    path('admin/seasons/<uuid:pk>/', AdminSeasonCRUDView.as_view(), name='admin-seasons-detail'),
]
