# Generated by Django 6.0.5 on 2026-05-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='allowed_methods',
            field=models.ManyToManyField(blank=True, related_name='majors', to='admissions.admissionmethod'),
        ),
    ]
