# Generated by Django 6.0.5 on 2026-05-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_major_allowed_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='allowed_combinations',
            field=models.ManyToManyField(blank=True, related_name='majors', to='admissions.subjectcombination'),
        ),
    ]
