# Generated by Django 6.0.5 on 2026-05-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_major_allowed_combinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionresult',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='majorbenchmark',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
