# Generated by Django 6.0.4 on 2026-05-01 11:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_workflow_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('round_number', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PLANNING', 'Đang lên kế hoạch'), ('OPEN', 'Đang mở đăng ký'), ('CLOSED', 'Đã đóng đăng ký'), ('PROCESSING', 'Đang xét tuyển'), ('COMPLETED', 'Hoàn thành')], default='PLANNING', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admission_seasons',
                'ordering': ['-year', '-round_number'],
                'unique_together': {('year', 'round_number')},
            },
        ),
    ]
