# Generated by Django 6.0.4 on 2026-05-05 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_add_season_to_applications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissionmethod',
            options={},
        ),
        migrations.AlterModelOptions(
            name='admissionresult',
            options={},
        ),
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='major',
            options={},
        ),
        migrations.AlterModelOptions(
            name='majorbenchmark',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoreformula',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subjectcombination',
            options={},
        ),
    ]
